### ISSUE TITLE
Hacktoberfest: Text search over wines demo update

### ISSUE THREAD

**Issue by iamleonie** [weaviate-tutorials/DEMO-text-search-wines#1]
This is the tracker for polishing the “Wine search” demo. Please refer to our [Hacktoberfest 2023 blog](https://weaviate.io/blog/hacktoberfest-2023) if you want to contribute! 

List of items to contribute:

- [x]  Run the existing demo and identify and document what exists and what is or isn’t working for the next task
- [x]  Fixes for any of the identified issues 
    - [x] Pandas version in requirements.txt was old and wouldn't run locally.
    - [x] In the docker-compose.yml file the ports was mapping to 8081 instead of 8080
    - [x] In the docker-compose.yml file the weaviate image was older which caused the import code to error out and when that was fixed an error in weaviate itself occured. 
    - [x] Issue identified here: https://github.com/weaviate-tutorials/DEMO-text-search-wines/issues/5
- [ ]  Update README to include:
    - [x] Short description
    - [x] used technology
        - [ ] used Weaviate modules/ML models
    - [ ]  demo video
    - [x] Prerequisites
    - [x] Setup instructions
    - [x] Usage instructions
    - [x] Dataset license if applicable
- [ ] Possible improvements/enhancements
    - [ ] Separate front end and backend (Could be React / Streamlit / whatever, with Node / Flask / FastAPI etc.) (claimed by @markgunnels)
    - [ ] Add semantic search to enable things like "wine that goes well with salmon"
    - [ ] Add progress bar to import file
    - [ ] Add generative search to do something like descriptions of wine varieties
    - [ ] Add filters for varieties / origins
    - [ ] Add ‘nearObject’ type searches to recommend similar wines (claimed by @miniMaddy)
    - [ ] Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point) (claimed by @markgunnels)
    - [x] Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)
        - [ ] After Weaviate release 1.22: swap out preview image
    - [x] Optional: Explore similar projects with another dataset (@Devanshu-17 )

**We're open to further suggestions. If you have any further potential improvement ideas, let us know in the comments!**

📣You can contribute parts of the issue or the whole issue. Please comment below to volunteer for the part(s) you want to contribute to.

❓For any questions you might have along the way, join our [Discourse community forum](https://forum.weaviate.io/t/welcome-to-hacktoberfest-2023/764), where we're ready to answer your questions. Or join our dedicated #hacktoberfest channel in our [Weaviate Community Slack](https://weaviate.slack.com/) channel to stay connected and receive real-time support.

✅For your PR, please mention this issue and set @iamleonie as the reviewer and we will review your PR shortly.

**Comment by markgunnels** [comment]
I'd gladly work this issue to completion.

**Comment by iamleonie** [comment]
@markgunnels Thank you for volunteering. Please note that the tasks under "Possible improvements" are suggestions and don't all have to be completed. Please let others and us know which task(s) you are working on so others can work in parallel on other tasks with you :)

**Comment by markgunnels** [comment]
For whomever else might be contributing:
I ran through getting everything set up and captured the issues with getting it running as it stands. 
" <-- List any identified issues here (e.g., data ingestion, search, back-end/API, front-end) --> "

1.  Pandas version in requirements.txt was old and wouldn't run locally.
2. In the docker-compose.yml file the ports was mapping to 8081 instead of 8080 
3. In the docker-compose.yml file the weaviate image was older which caused the import code to error out and when that was fixed an error in weaviate itself occured. The error was: "demo-text-search-wines-weaviate-1          | 2023/10/03 09:29:55 http: panic serving 172.21.0.1:37746: write tcp 172.21.0.2:8080->172.21.0.1:37746: i/o timeout"

Once those were fixed the code worked. I'll clean that up and create a PR. I'll start on the README.md items next.

Here is the query I ran copied from the article (included here since it's contained in an image):
{
  Get {
    Wine (
      limit: 3
      nearText: {
        concepts: ["wine that fits with fish"]
      }
    ) {
      title
      description
    }
  }
}

**Comment by miniMaddy** [comment]
Hello, I would like to work on this issue. I am particularly interested in "Possible improvements/enhancements" part. What parts are you working on @markgunnels ?

**Comment by markgunnels** [comment]
Hi @miniMaddy -

I was going to start updating the README.md before moving to the Possible improvements/enhancements so if you want to start on those no worries!

Cheers,
MG

**Comment by markgunnels** [comment]
@iamleonie @miniMaddy 

I'll try and make a video and update the readme.md with further instructions such as example queries. 
Before that I'd like to work on the following tasks if y'all have no objections:

- Adding tests (e.g., Pytest, Jest, etc. See our [example](https://github.com/databyjp/distyll) for a starting point)
- Conversion to new [Weaviate Python client](https://weaviate.io/blog/collections-python-client-preview)

**Comment by miniMaddy** [comment]
Hey, @markgunnels , sorry but I have started working on the new weaviate client. Can I please complete it?

**Comment by shu3hamiitkgp** [comment]
I'd like to start working on the 'Add generative search to do something like descriptions of wine varieties' in the possible improvements, @markgunnels  , @miniMaddy can you guys pls give me a heads up if you're already working on that?

**Comment by miniMaddy** [comment]
Hey, I am not working on that, you can go ahead :)

**Comment by markgunnels** [comment]
@shu3hamiitkgp  If you get a chance can you let me know if you are still working on the generative search? Cheers!

**Comment by iamleonie** [comment]
Hi @markgunnels, @shu3hamiitkgp,
to get a better overview for new contributors of which tasks already have people working on them I added your names to some tasks in the issues description.

Kindly, review if my understanding is correct and please let me know if I need to change something. Also, if you want to switch to a different task, don't hesitate to ping me and we will "unclaim" the task :)

**Comment by miniMaddy** [comment]
Hi @iamleonie , I would like to take the 'nearObjects' issue.

**Comment by shu3hamiitkgp** [comment]
> @shu3hamiitkgp If you get a chance can you let me know if you are still working on the generative search? Cheers!

Yes @markgunnels, I'm working on it.

**Comment by Devanshu-17** [comment]
Hi, I would like to contribute to these topics. Can anyone please tell me if they are available

1. Separate front end and backend  - **Using Gradio**

2.  Optional: Explore similar projects with **another** dataset

I was thinking of first trying different datasets locally and then allow the users to upload their own datasets for real time search

@markgunnels @shu3hamiitkgp @iamleonie @miniMaddy

**Comment by iamleonie** [comment]
Hi @Devanshu-17,
Thanks for volunterring!
The "Separate front end and backend" task is already taken by @markgunnels 
Would you still like to take on the "Optional: Explore similar projects with another dataset" task?

**Comment by Devanshu-17** [comment]
Hi @iamleonie 

I would be glad to create a demo with another dataset

**Comment by iamleonie** [comment]
Awesome @Devanshu-17, I will tag you in the task.

**Comment by Devanshu-17** [comment]
Hey @iamleonie,

I have created a pull request containing the demo with a different dataset. Can you please take a look and do let me know if you need any further information or if any changes are need to be made. 🤗

**Comment by iamleonie** [comment]
Hey @markgunnels and @shu3hamiitkgp,
since it's the last week of Hacktoberfest, I wanted to quickly check in with you to see how things are going.
Please don't hesitate to reach out here or on our [Community Slack](https://weaviate.io/slack) if you need any assistance.
We can also un-claim the tasks if you are no longer working on the tasks.

**Comment by shu3hamiitkgp** [comment]
Hi @iamleonie,
I'll un-claim the generative search feature, for now, I got busy with other commitments. In case it is open in the future, I'll definitely get back to it

**Comment by iamleonie** [comment]
Thanks for the feedback @shu3hamiitkgp. Totally understandable! I have unclaimed the task.

**Comment by iamleonie** [comment]
Thank you, everyone, for contributing to a successful Hacktoberfest 2023!

This issue will now be closed.

If you are still working on any topics, you can, of course, continue on them. However, please note that any PRs created after Oct 31st will not count towards Hacktoberfest.
